language: ruby
bundle_args: "--without development"
before_script: bundle exec rake db:create db:migrate
addons:
  code_climate:
    repo_token: 71b1dd77bbae47780e056659e42a580fc3e6292cbecea7c0a2163c85a88fa6cf
notifications:
  slack:
    secure: iTPF17cLWd/yL9hmABQMXHOHdc1eH1fNrBD6bgwtqw0g0osF11WElzF/lAHqhCXIJgqH8VhGjQxuM2DidbDVGLUIq0476iTewTMsATdv96MOllRitFePdpm4tQ0PylhkCjPoWTmQ3L0A5UD5wNspdujGMXxCu18/AeP33AeVzfo=
rvm:
- 2.1.0
